query ListPitches @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as it only lists pitch details.") {
  pitches {
    id
    name
    location
    surfaceType
    hourlyRate
    imageUrl
  }
}

mutation CreateReservation(
  $pitchId: UUID!,
  $availabilitySlotId: UUID!,
  $totalPrice: Float!
) @auth(level: USER, insecureReason: "Requires logged-in user context.") {
  reservation_insert(data: {
    pitchId: $pitchId,
    availabilitySlotId: $availabilitySlotId,
    totalPrice: $totalPrice,
    bookingTime_expr: "request.time",
    status: "PENDING",
    userId_expr: "auth.uid"
  })
}

query MyReservations @auth(level: USER) {
  reservations(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    bookingTime
    status
    totalPrice
    pitch {
      name
      location
    }
    availabilitySlot {
      startTime
      endTime
      date
    }
  }
}

mutation AddPitchReview(
  $pitchId: UUID!,
  $rating: Int!,
  $comment: String
) @auth(level: USER, insecureReason: "Requires logged-in user context.") {
  review_insert(data: {
    pitchId: $pitchId,
    rating: $rating,
    comment: $comment,
    createdAt_expr: "request.time",
    userId_expr: "auth.uid"
  })
}